ruby-web-service:
  image:
    name: "r.cfcr.io/g5dev/social-feed"
  isInternetFacing: true
  hasMetrics: true
  hasDatabase: false
  customTypeCollectors:
    - "collectors/model_rows_collector.rb"
  configurations:
    production:
    staging:
  honeybadgerAPIKey: "b8a42b12"
  features:
    - "scout"
    - "g5-auth-oauth-app"
    - "g5-auth-service-to-service-client"
  rails:
    replicas: 2
    concurrency: 5
    resources:
      requests:
        memory: "600Mi"
        cpu: "200m"
      limits:
        memory: "600Mi"
        cpu: "1000m"
  env:
    - name: REDIS_URL
      valueFrom:
        configMapKeyRef:
          name: social-feed-cache-memorystore
          key: cache-store-url
    - name: FACEBOOK_APP_ID
      valueFrom:
        secretKeyRef:
          name: social-feed 
          key: facebook-app-id
    - name: FACEBOOK_APP_SECRET
      valueFrom:
        secretKeyRef:
          name: social-feed 
          key: facebook-app-secret
    - name: GOOGLE_PLUS_API_KEY
      valueFrom:
        secretKeyRef:
          name: social-feed 
          key: google-plus-api-key
    - name: INSTAGRAM_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          name: social-feed 
          key: instagram-access-token
    - name: TWITTER_CONSUMER_KEY
      valueFrom:
        secretKeyRef:
          name: social-feed 
          key: twitter-consumer-key
    - name: TWITTER_CONSUMER_SECRET
      valueFrom:
        secretKeyRef:
          name: social-feed 
          key: twitter-consumer-secret
    - name: WALKSCORE_API_KEY
      valueFrom:
        secretKeyRef:
          name: social-feed 
          key: walkscore-api-key
