apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    dalton.getg5.com/application: |-
      {
        "imageTags": [
          { "containerName": "rails-server" }
        ]
      }
  name: social-feed-service-rails-servers
  labels:
    app: social-feed-service
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "75%"
      maxSurge: 1
  selector:
    matchLabels:
      app: social-feed-service
      tier: web-app
  template:
    metadata:
      name: rails-server
      labels:
        app: social-feed-service
        tier: web-app
    spec:
      imagePullSecrets:
        - name: docker-registry-service-account
      containers:
        - name: rails-server
          image: g5search/g5-social-feed-service
          command: [ "bundle", "exec", "rails", "s" ]
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /okcomputer
              port: http
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 15
            timeoutSeconds: 10
            failureThreshold: 6
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /okcomputer
              port: http
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 15
            timeoutSeconds: 10
            failureThreshold: 6
            periodSeconds: 10
          resources:
            requests:
              memory: "768Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: RAILS_ENV
              value: production
            - name: RACK_ENV
              value: production
            # tier-specific
            - name: PUMA_CONCURRENCY
              value: "2"
            #app-specific
            - name: FACEBOOK_APP_ID
              valueFrom:
                secretKeyRef:
                  name: social-feed-service
                  key: facebook-app-id
            - name: FACEBOOK_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: social-feed-service
                  key: facebook-app-secret
            - name: GOOGLE_PLUS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: social-feed-service
                  key: google-plus-api-key
            - name: INSTAGRAM_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: social-feed-service
                  key: instagram-access-token
            - name: TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: social-feed-service
                  key: twitter-consumer-key
            - name: TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: social-feed-service
                  key: twitter-consumer-secret
            - name: WALKSCORE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: social-feed-service
                  key: walkscore-api-key
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: social-feed-service
                  key: secret-key-base
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: social-feed-service
                  key: new-relic-license-key
            - name: NEW_RELIC_APP_NAME
              valueFrom:
                secretKeyRef:
                  name: social-feed-service
                  key: new-relic-app-name
            - name: SKYLIGHT_AUTHENTICATION
              valueFrom:
                secretKeyRef:
                  name: social-feed-service
                  key: skylight-authentication
            # namespace-specific
            - name: G5_AUTH_ALLOW_PASSWORD_CREDENTIALS
              value: "true"
            - name: G5_AUTH_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: g5-auth
                  key: endpoint
            - name: G5_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: g5-auth
                  key: service-account-username
            - name: G5_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: g5-auth
                  key: service-account-password
