{
 "title": "Social Feed",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Rails", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage by Pod 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "container_cpu_usage_percentage:sum_rate5m{pod_name=~\"^social-feed-rails-servers.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod_name=~\"^social-feed-rails-servers.*\",container_name=\"\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Puma Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ruby_puma_max_threads_total{pod=~\"social-feed-.*\"})",
     "legendFormat": "Total Threads"
    },
    {
     "expr": "sum(ruby_puma_running_threads_total{pod=~\"social-feed-.*\"})",
     "legendFormat": "Running Threads"
    },
    {
     "expr": "sum(ruby_puma_request_backlog_total{pod=~\"social-feed-.*\"})",
     "legendFormat": "Request Backlog"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"social-feed.default.svc.cluster.local\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"social-feed.default.svc.cluster.local\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"social-feed.default.svc.cluster.local\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Incoming Requests by Destination And Response Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",destination_service=~\"social-feed.default.svc.cluster.local\",reporter=\"destination\",destination_workload=~\"social-feed-rails-servers\",destination_workload_namespace=~\"default\"}[30s])) by (destination_workload, destination_workload_namespace, response_code), 0.001) > 0",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_service=~\"social-feed.default.svc.cluster.local\", reporter=\"destination\", destination_workload=~\"social-feed-rails-servers\", destination_workload_namespace=~\"default\"}[30s])) by (destination_workload, destination_workload_namespace, response_code), 0.001) > 0",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Proxy Requests By Method/Response Code 5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(traefik_entrypoint_requests_total{pod=~\"^social-feed-metrics-proxy.*\"}[5m])",
     "legendFormat": "{{method}}/{{code}}"
    }
   ]
  },
  {
   "title": "Proxy GET Requests 5m",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_request_duration_seconds_bucket{method=\"GET\", pod=~\"^social-feed-metrics-proxy.*\"}[5m])) by (le)"
    }
   ]
  },
  {
   "title": "Metrics Meta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sidecar Container Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=\"default\", pod_name=~\"^social-feed.*\", container_name=\"prometheus-exporter\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Metrics 5m",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(ruby_collector_metrics_total{pod=~\"social-feed.*\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Global Exporter CPU Usage 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "container_cpu_usage_percentage:sum_rate5m{pod_name=~\"^social-feed-global-metrics-exporter.*\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Global Exporter Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod_name=~\"^social-feed-global-metrics-exporter.*\",container_name=\"\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}